version: '3'
services:
  app:
    container_name: main_project
    build: .
    ports: 
      - 8000:8000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - main_project-postgres          
    networks:
      - main_project


  main_project-postgres:
    image: postgres:latest
    container_name: main_project
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - main_project
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - main_project-postgres
    ports:
      - "5050:80"
    networks:
      - main_project
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  main_project:
    driver: bridge